export class CSVRecord {
    public correo: string;
    public nombre: string;
    public apellido: string;
    public telefono: number;
    public direccion: string;
    public identificacion: number;
    public tipo_id: string;
    public fecha_ingreso: any;
    public cuenta_bancaria :    string;
    public total_otros_ahorros  :  number;
    // public cuentaBancaria: any;
    // public totalOtrosAhorros: any;
    // public saldoAportes: any;
    // public cuotaAportes: any;
    // public aportesOrdinarios: any;
    // public ahorropermanente: any;
    // public saldoCartera: any;
    // public numeroCreditos: any;
    // public tipoCadaCredito: any;
    // public saldoCarteraCadaCredito: any;
    // public tasaCadaCredito: any;
    // public plazoCadaCredito: any;
    // public moraCadaCredito: any;
    // public fechaSolicitudCadaCredito: any;
    // public fechaDesembolsoCadaCredito: any;
    // public fechaInicioPagoCadaCredito: any;
    // public coutasPendientesCadaCredito: any;
    // public coutaCarteraCadaCredito: any;
    // public valorInteresesCadaCuota: any;
    // public valorSeguroCadaCouta: any;
    // public valorAporteCapitalCadaCuota: any;
    // public saldoAhorros: any;
    // public numeroAhorros: any;
    // public saldoAhorrosdeCadaAhorro: any;
    // public tasaCadaAhorro: any;
    // public coutaAhorroCadaAhorro: any;
    // public fechaSolicitudCadaAhorro: any;
    // public fechaInicioAporteCadaAhorro: any;
    // public saldoServicios: any;
    // public numeroServicios: any;
    // public nombreCadaServicio: any;
    // public saldoServicioCadaServicio: any;
    // public plazoCadaServicio: any;
    // public moraCadacredito: any;
    // public fechaSolicituCadaServicio: any;
    // public fechaInicioCadaServicio: any;
    // public fechaInicioPagoCadaServicio: any;
    // public coutasPendientesCadaServicio: any;
    // public tasaCadaServicio: any;
    // public coutaServicioCadaServicio: any;
    // public valorInteresesCadaCuotaServicio: any;
    // public valorSeguroCadaCuotaServicio: any;
    // public valorAporteCapitalCadaCuotaServicio: any;
}